# Generated by Django 5.1.1 on 2024-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('course', models.CharField(blank=True, choices=[('cse', 'cyber security'), ('iot', 'internet of things'), ('ai', 'Artificial Intelligence & data science')], max_length=3, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True)),
                ('question_text', models.CharField(max_length=500)),
            ],
        ),
    ]
